@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

GET http://{{host}}/usuario 

###
GET http://{{host}}/usuario/2

###
POST http://{{host}}/usuario
content-type: {{contentType}}

{
    "nome": "Usuario Teste",
    "email": "teste@root.com",
    "senha": "root@root"
}

###
DELETE http://{{host}}/usuario/4

###
PATCH http://{{host}}/usuario/5
content-type: {{contentType}}

{
    "nome": "Usuario Administrador",
    "email": "teste@admin.com",
    "senha": "root@admin"
}